name: TradingAssistantApp
dependencies:
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - click=8.0.1
  - colorama=0.4.4
  - cycler=0.10.0
  - flask=1.1.2
  - fonttools=4.25.0
  - freetype=2.10.4
  - future=0.18.2
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib-metadata=4.6.4
  - iniconfig=1.1.1
  - intel-openmp=2021.3.0
  - itsdangerous=2.0.1
  - jinja2=3.0.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=8.8.0
  - munkres=1.1.4
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - pillow=8.4.0
  - pip=21.0.1
  - pluggy=0.13.1
  - py=1.10.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pytest=6.2.4
  - python=3.8.11
  - python-dateutil=2.8.2
  - pytz=2021.3
  - qt=5.9.7
  - scipy=1.7.1
  - seaborn=0.11.2
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=1.0.1
  - wheel=0.37.0
  - wincertstore=0.2
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - boto3==1.19.5
    - botocore==1.22.5
    - charset-normalizer==2.0.7
    - idna==3.3
    - jmespath==0.10.0
    - lxml==4.6.3
    - multitasking==0.0.9
    - requests==2.26.0
    - s3transfer==0.5.0
    - urllib3==1.26.7
    - yfinance==0.1.64
